"use client"

import { useMemo, useState } from "react"
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { Bell, BriefcaseBusiness, CalendarDays, ChevronDown, CircleHelp, CreditCard, FileText, LayoutDashboard, Menu, Plus, Receipt, Search, Settings, TrendingDown, TrendingUp, Wallet, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"

const menu = [
  { label: "Visão geral", icon: LayoutDashboard },
  { label: "Faturamento", icon: Receipt },
  { label: "Despesas", icon: CreditCard },
  { label: "Fluxo de caixa", icon: Wallet },
  { label: "Investimentos", icon: TrendingUp },
  { label: "Orçamento", icon: FileText },
  { label: "Metas", icon: BriefcaseBusiness },
]
const monthly = [{ name: "Jan", receita: 58, despesa: 34 }, { name: "Fev", receita: 65, despesa: 38 }, { name: "Mar", receita: 62, despesa: 35 }, { name: "Abr", receita: 76, despesa: 43 }, { name: "Mai", receita: 72, despesa: 42 }, { name: "Jun", receita: 84, despesa: 46 }]
const initialTransactions = [
  { name: "Recebimento — Tech Solutions", category: "Faturamento", date: "Hoje, 09:42", value: 12450, positive: true },
  { name: "Google Workspace", category: "Operacional", date: "Ontem, 16:20", value: -890, positive: false },
  { name: "CDB — Banco Inter", category: "Investimentos", date: "Ontem, 11:05", value: -5000, positive: false },
  { name: "Recebimento — Agência Norte", category: "Faturamento", date: "12 Jun, 14:18", value: 8350, positive: true },
]
const investments = [{ name: "Renda fixa", value: 42000, color: "#183b56" }, { name: "Fundos", value: 18500, color: "#2f7f70" }, { name: "Ações", value: 9800, color: "#e2a84a" }]
const money = (n: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }).format(n)

export default function Home() {
  const [active, setActive] = useState("Visão geral")
  const [open, setOpen] = useState(false)
  const [transactions, setTransactions] = useState(initialTransactions)
  const [query, setQuery] = useState("")
  const totalIn = transactions.filter(t => t.positive).reduce((a, t) => a + t.value, 0)
  const totalOut = transactions.filter(t => !t.positive).reduce((a, t) => a + Math.abs(t.value), 0)
  const filtered = useMemo(() => transactions.filter(t => t.name.toLowerCase().includes(query.toLowerCase()) || t.category.toLowerCase().includes(query.toLowerCase())), [transactions, query])
  const addTransaction = () => setTransactions([{ name: "Novo lançamento", category: "Operacional", date: "Agora", value: 1200, positive: false }, ...transactions])

  return <div className="min-h-screen bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-20 flex w-64 flex-col border-r border-border bg-card p-5 transition-transform lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex items-center justify-between px-2 pb-8"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Wallet /></div><span className="font-sans text-lg font-bold tracking-tight">Nexo<span className="text-accent-foreground">.</span></span></div><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setOpen(false)}><X /></Button></div>
      <div className="mb-7 rounded-xl bg-secondary p-3"><p className="text-xs text-muted-foreground">Empresa ativa</p><div className="mt-1 flex items-center justify-between"><p className="font-semibold">Nexo Tecnologia</p><ChevronDown className="size-4 text-muted-foreground" /></div><p className="mt-1 text-xs text-muted-foreground">CNPJ 12.345.678/0001-90</p></div>
      <nav className="flex flex-col gap-1">{menu.map(item => { const Icon = item.icon; return <button key={item.label} onClick={() => { setActive(item.label); setOpen(false) }} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition-colors ${active === item.label ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:bg-secondary hover:text-foreground"}`}><Icon className="size-4" />{item.label}</button> })}</nav>
      <div className="mt-auto flex flex-col gap-1 border-t border-border pt-4"><button className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-secondary"><Settings className="size-4" />Configurações</button><button className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-secondary"><CircleHelp className="size-4" />Central de ajuda</button><div className="mt-4 flex items-center gap-3 rounded-lg bg-secondary p-3"><div className="flex size-8 items-center justify-center rounded-full bg-accent text-sm font-semibold text-accent-foreground">MS</div><div><p className="text-sm font-medium">Marina Silva</p><p className="text-xs text-muted-foreground">Administradora</p></div></div></div>
    </aside>
    {open && <button aria-label="Fechar menu" className="fixed inset-0 z-10 bg-foreground/20 lg:hidden" onClick={() => setOpen(false)} />}
    <div className="lg:pl-64"><header className="flex h-20 items-center justify-between border-b border-border bg-card px-5 md:px-10"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setOpen(true)}><Menu /></Button><div><p className="text-sm text-muted-foreground">Segunda-feira, 16 de junho de 2025</p><h1 className="font-sans text-xl font-bold tracking-tight">{active}</h1></div></div><div className="flex items-center gap-2 md:gap-4"><div className="relative hidden md:block"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar lançamentos" className="w-56 pl-9" /></div><Button variant="ghost" size="icon" aria-label="Notificações"><Bell className="size-4" /></Button><Button onClick={addTransaction} className="hidden sm:flex"><Plus data-icon="inline-start" />Lançamento</Button></div></header>
      <main className="mx-auto max-w-[1440px] p-5 md:p-10"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-sm font-medium text-accent-foreground">Resumo financeiro</p><h2 className="font-sans text-3xl font-bold tracking-tight text-balance">Bom dia, Marina.</h2><p className="mt-2 text-muted-foreground">Veja como está a saúde financeira da sua empresa.</p></div><Button variant="outline"><CalendarDays data-icon="inline-start" />Junho 2025<ChevronDown data-icon="inline-end" /></Button></div>
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi title="Saldo em conta" value={money(128450)} change="+12,8%" icon={Wallet} tone="primary" /><Kpi title="Faturamento" value={money(totalIn + 63450)} change="+8,4%" icon={TrendingUp} tone="green" /><Kpi title="Despesas" value={money(totalOut + 28650)} change="-3,2%" icon={TrendingDown} tone="amber" negative /><Kpi title="Lucro líquido" value={money(48200)} change="+16,5%" icon={BriefcaseBusiness} tone="blue" /></section>
        <div className="mt-6 grid gap-6 xl:grid-cols-[1.6fr_1fr]"><Card><CardHeader className="flex flex-row items-start justify-between"><div><CardTitle>Evolução financeira</CardTitle><CardDescription>Receitas e despesas nos últimos 6 meses</CardDescription></div><Badge variant="secondary" className="font-normal">Mensal <ChevronDown className="ml-1 size-3" /></Badge></CardHeader><CardContent><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthly}><defs><linearGradient id="receita" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2f7f70" stopOpacity={0.25}/><stop offset="100%" stopColor="#2f7f70" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e7ecec" /><XAxis dataKey="name" axisLine={false} tickLine={false} tickMargin={10} /><YAxis axisLine={false} tickLine={false} tickFormatter={v => `R$${v}k`} /><Tooltip formatter={(v) => [`R$ ${v} mil`, ""]} /><Area type="monotone" dataKey="receita" stroke="#2f7f70" fill="url(#receita)" strokeWidth={2.5} /><Area type="monotone" dataKey="despesa" stroke="#e2a84a" fill="none" strokeWidth={2} /></AreaChart></ResponsiveContainer></div><div className="flex gap-5 text-xs text-muted-foreground"><span><i className="mr-2 inline-block size-2 rounded-full bg-chart-2" />Receitas</span><span><i className="mr-2 inline-block size-2 rounded-full bg-chart-4" />Despesas</span></div></CardContent></Card>
        <Card><CardHeader><CardTitle>Distribuição de investimentos</CardTitle><CardDescription>Patrimônio investido: {money(70300)}</CardDescription></CardHeader><CardContent><div className="h-48"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={investments} dataKey="value" nameKey="name" innerRadius={55} outerRadius={78} paddingAngle={3}>{investments.map(i => <Cell key={i.name} fill={i.color} />)}</Pie><Tooltip formatter={v => money(Number(v))} /></PieChart></ResponsiveContainer></div><div className="flex flex-col gap-3">{investments.map(i => <div className="flex items-center justify-between text-sm" key={i.name}><span className="flex items-center gap-2"><i className="size-2 rounded-full" style={{ backgroundColor: i.color }} />{i.name}</span><span className="font-semibold">{money(i.value)}</span></div>)}</div></CardContent></Card></div>
        <div className="mt-6 grid gap-6 xl:grid-cols-[1.6fr_1fr]"><Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Últimas movimentações</CardTitle><CardDescription>Entradas e saídas recentes</CardDescription></div><Button variant="ghost" className="text-accent-foreground">Ver todas</Button></CardHeader><CardContent><div className="flex flex-col">{filtered.map((t, i) => <div className={`flex items-center justify-between gap-3 py-4 ${i ? "border-t border-border" : ""}`} key={`${t.name}-${i}`}><div className="flex min-w-0 items-center gap-3"><div className={`flex size-9 shrink-0 items-center justify-center rounded-lg ${t.positive ? "bg-accent text-accent-foreground" : "bg-secondary text-muted-foreground"}`}>{t.positive ? <TrendingUp className="size-4" /> : <CreditCard className="size-4" />}</div><div className="min-w-0"><p className="truncate text-sm font-medium">{t.name}</p><p className="text-xs text-muted-foreground">{t.category} · {t.date}</p></div></div><p className={`shrink-0 text-sm font-semibold ${t.positive ? "text-accent-foreground" : "text-foreground"}`}>{t.positive ? "+" : "−"}{money(Math.abs(t.value))}</p></div>)}</div></CardContent></Card>
        <Card><CardHeader><CardTitle>Orçamento mensal</CardTitle><CardDescription>Acompanhe seus limites por categoria</CardDescription></CardHeader><CardContent><div className="flex flex-col gap-5">{[["Operacional", 72, "R$ 18.400 / R$ 25.500"], ["Marketing", 48, "R$ 7.200 / R$ 15.000"], ["Pessoal", 86, "R$ 31.600 / R$ 36.800"]].map(([name, value, text]) => <div key={String(name)}><div className="mb-2 flex justify-between text-sm"><span className="font-medium">{name}</span><span className="text-muted-foreground">{text}</span></div><div className="h-2 overflow-hidden rounded-full bg-secondary"><div className={`h-full rounded-full ${Number(value) > 80 ? "bg-chart-4" : "bg-chart-2"}`} style={{ width: `${value}%` }} /></div></div>)}</div><Button variant="outline" className="mt-7 w-full">Gerenciar orçamento</Button></CardContent></Card></div>
      </main></div></div>
}
function Kpi({ title, value, change, icon: Icon, tone, negative }: { title: string; value: string; change: string; icon: React.ElementType; tone: string; negative?: boolean }) { return <Card><CardContent className="p-5"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{title}</span><span className={`flex size-8 items-center justify-center rounded-lg ${tone === "primary" ? "bg-primary text-primary-foreground" : tone === "green" ? "bg-accent text-accent-foreground" : "bg-secondary text-muted-foreground"}`}><Icon className="size-4" /></span></div><p className="mt-4 font-sans text-2xl font-bold tracking-tight">{value}</p><p className={`mt-2 text-xs ${negative ? "text-chart-2" : "text-accent-foreground"}`}><span className="font-semibold">{change}</span> <span className="text-muted-foreground">vs. mês anterior</span></p></CardContent></Card> }
